export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const REGISTER_OTP = 'REGISTER_OTP';
export const REGISTER_OTP_SUCCESS = 'REGISTER_OTP_SUCCESS';
export const REGISTER_OTP_FAILED = 'REGISTER_OTP_FAILED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const SET_AUTH = 'SET_AUTH';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const SET_SEE_LANDING = 'SET_SEE_LANDING';
export const SET_COUNTRY = 'SET_COUNTRY';

export const GET_LIST_COUNTRY = 'GET_LIST_COUNTRY';
export const GET_LIST_COUNTRY_SUCCESS = 'GET_LIST_COUNTRY_SUCCESS';
export const GET_LIST_COUNTRY_FAILED = 'GET_LIST_COUNTRY_FAILED';

export const GET_LIST_REFRESH_COUNTRY = 'GET_LIST_REFRESH_COUNTRY';
export const GET_LIST_REFRESH_COUNTRY_SUCCESS =
  'GET_LIST_REFRESH_COUNTRY_SUCCESS';
export const GET_LIST_REFRESH_COUNTRY_FAILED =
  'GET_LIST_REFRESH_COUNTRY_FAILED';

export const GET_LIST_PAGING_COUNTRY = 'GET_LIST_PAGING_COUNTRY';
export const GET_LIST_PAGING_COUNTRY_SUCCESS =
  'GET_LIST_PAGING_COUNTRY_SUCCESS';
export const GET_LIST_PAGING_COUNTRY_FAILED = 'GET_LIST_PAGING_COUNTRY_FAILED';
