export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';

export const GET_FILM = 'GET_FILM';
export const GET_FILM_SUCCESS = 'GET_FILM_SUCCESS';
export const GET_FILM_FAILED = 'GET_FILM_FAILED';

export const GET_FILM_DETAIL = 'GET_FILM_DETAIL';
export const GET_FILM_DETAIL_SUCCESS = 'GET_FILM_DETAIL_SUCCESS';
export const GET_FILM_DETAIL_FAILED = 'GET_FILM_DETAIL_FAILED';

export const GET_FILM_UPCOMING = 'GET_FILM_UPCOMING';
export const GET_FILM_UPCOMING_SUCCESS = 'GET_FILM_UPCOMING_SUCCESS';
export const GET_FILM_UPCOMING_FAILED = 'GET_FILM_UPCOMING_FAILED';

export const GET_FILM_POPULAR = 'GET_FILM_POPULAR';
export const GET_FILM_POPULAR_SUCCESS = 'GET_FILM_POPULAR_SUCCESS';
export const GET_FILM_POPULAR_FAILED = 'GET_FILM_POPULAR_FAILED';
